services:
  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=card_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d card_db" ]
      interval: 5s
      timeout: 5s
      retries: 5


  app:
    container_name: card-app
    build: .
    ports:
      - "8080:8080"
    depends_on:
      postgres-db:
        condition: service_healthy

volumes:
  postgres-data:
